ALTER TABLE `ragnarok`.`char` 
ADD COLUMN `pow` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `luk`,
ADD COLUMN `sta` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `pow`,
ADD COLUMN `wis` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `sta`,
ADD COLUMN `spl` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `wis`,
ADD COLUMN `con` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `spl`,
ADD COLUMN `crt` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `con`,
ADD COLUMN `max_ap` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `sp`,
ADD COLUMN `ap` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `max_ap`,
ADD COLUMN `trait_point` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `status_point`;
